In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import matplotlib
%matplotlib inline
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Final_Dataset.csv')
df.head()

CLAIM_NUMBER  LINE_NUMBER  MEMBER_NUMBER  CURRENTAGE SUFFIX PATIENTNAME  \
0         31184            1    30400166634   39.921212      2  TASHINGA     
1         56041            1    30400171454   36.948093      1     EMILY     
2         86876            1    30001814165   38.128201      1    FADZAI     
3        117280            1    40000064456   60.203470      2    BHAVNA     
4        117281            1    40000064456   60.203470      2    BHAVNA     

  GENDER  CURRENTAGE_1  CLAIMED   PAID  ...  REFERRAL  PCKAGE TARIFF_AMOUNT  \
0      F     39.921212    450.0  258.0  ...   10782.0     304         258.0   
1      F     36.948093     70.0   17.5  ...    1244.0     304          25.0   
2      F     38.128201     25.0   17.5  ...    5058.0     300          25.0   
3      F     60.203470    300.0  135.0  ...   18192.0     400         135.0   
4      F     60.203470    200.0  200.0  ...   18192.0     400         250.0   

   PAY_WHO MODIFIER_STRING     FIRMNO SHORTFALLREASON PROVIDERTYPE       AGE  \
0        M             NaN  CMS004KAO             101           18  ABOVE 22   
1        M             NaN  CMS004MUR             101           18  ABOVE 22   
2        M             NaN  CMS001TNQ             101           18  ABOVE 22   
3        V             NaN  CMS001SHC         101;535           18  ABOVE 22   
4        V             NaN  CMS001SHC             101           18  ABOVE 22   

     Class  
0  proceed  
1  proceed  
2  proceed  
3  proceed  
4  proceed  

[5 rows x 32 columns]

In [4]:
df1 = df.drop(columns = ['LINE_NUMBER','SUFFIX','PATIENTNAME','CURRENTAGE_1','SHORTFALL', 'DATE_RECEIVED', 'PROCESS_DATE','PAYDATE','SERVICEDATE','DESCRIPTION_1','QUANTITY','REFERRAL','PCKAGE','PAY_WHO','MODIFIER_STRING','FIRMNO','SHORTFALLREASON','AGE'], axis = 1)

In [5]:
train_dataset = df1.drop(columns = ['SPE_SPECIALITY_CODE','PRACTICE_NAME','CLAIM_NUMBER','PROVIDERTYPE','TARIFF_AMOUNT','PAID'], axis = 1)

In [6]:
train_dataset = train_dataset.sample(frac=1).reset_index(drop=True)

In [7]:
train_dataset = train_dataset.replace({'GENDER':{'F':1,'M':0}})

In [8]:
train_dataset = train_dataset.replace({'Class':{'possible fraud ':0,'possible fraud':0, 'proceed':1}})

In [9]:
train_dataset

MEMBER_NUMBER  CURRENTAGE  GENDER  CLAIMED  PRACTICE_NUMBER  \
0        30000246915   37.450782       1     50.0            18228   
1        30001796582   42.770674       1     40.0           188851   
2        30000517755   26.964222       1     50.0           186588   
3        30001471749    4.356696       0     40.0            12009   
4        30001378999   47.681964       1     50.0            18686   
...              ...         ...     ...      ...              ...   
45849    30001373132    3.604007       1     80.0            12149   
45850    30001307177   35.241104       1    350.0            18176   
45851    40000291377   42.552932       1     25.0            18848   
45852    30002002519   33.243792       1     50.0            18635   
45853    30001338867   26.152394       1     35.0            18635   

                  DESCRIPTION  TARIFF_CODE  Class  
0      GYNAECOLOGY/OBSTETRICS        90030      1  
1      GYNAECOLOGY/OBSTETRICS        58101      1  
2      GYNAECOLOGY/OBSTETRICS        59475      1  
3              PAEDIATRICIANS        96993      1  
4      GYNAECOLOGY/OBSTETRICS        90030      1  
...                       ...          ...    ...  
45849          PAEDIATRICIANS        90003      1  
45850  GYNAECOLOGY/OBSTETRICS        59439      1  
45851  GYNAECOLOGY/OBSTETRICS        59477      1  
45852  GYNAECOLOGY/OBSTETRICS        59475      1  
45853  GYNAECOLOGY/OBSTETRICS        90033      1  

[45854 rows x 8 columns]

In [10]:
train_dataset = train_dataset.replace({'DESCRIPTION':{'GYNAECOLOGY/OBSTETRICS':1,'PAEDIATRICIANS':0}})

In [12]:
train_dataset = train_dataset.append({"MEMBER_NUMBER":4450,"CURRENTAGE":0,"GENDER":1,"CLAIMED":0,"PRACTICE_NUMBER":1,"DESCRIPTION":1,"TARIFF_CODE":765796,"Class":0},ignore_index=True)

train_dataset = train_dataset.append({"MEMBER_NUMBER":4353,"CURRENTAGE":1,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":3000,"DESCRIPTION":1,"TARIFF_CODE":88679,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":2,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":87667,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":45340,"CURRENTAGE":3,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":4000,"DESCRIPTION":1,"TARIFF_CODE":43466,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":4,"GENDER":1,"CLAIMED":10,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":676576,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":4534,"CURRENTAGE":5,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":78768,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":567,"CURRENTAGE":6,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":50000,"DESCRIPTION":1,"TARIFF_CODE":9788,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":7,"GENDER":1,"CLAIMED":4000,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":57887,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":4576,"CURRENTAGE":8,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":67676,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":234,"CURRENTAGE":9,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":98765,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":567,"CURRENTAGE":10,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":645545,"DESCRIPTION":1,"TARIFF_CODE":9545,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":11,"GENDER":1,"CLAIMED":500,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":9865,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":897,"CURRENTAGE":12,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":5678,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":13,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":67689,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3563,"CURRENTAGE":14,"GENDER":1,"CLAIMED":1000,"PRACTICE_NUMBER":43,"DESCRIPTION":1,"TARIFF_CODE":87876,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":24645,"CURRENTAGE":15,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":57676,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":56756,"CURRENTAGE":16,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":346,"DESCRIPTION":1,"TARIFF_CODE":74678,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3753,"CURRENTAGE":17,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":67687,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":68578,"CURRENTAGE":0,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":597500,"DESCRIPTION":1,"TARIFF_CODE":5789,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":47646,"CURRENTAGE":1,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":43345,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":5476, "CURRENTAGE":2,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":4345646,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":4752,"CURRENTAGE":3,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":876,"DESCRIPTION":1,"TARIFF_CODE":45466,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":2524,"CURRENTAGE":4,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":1000,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":2546,"CURRENTAGE":5,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":46766,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":8463,"CURRENTAGE":6,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":86566,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":5765,"CURRENTAGE":7,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":0,"DESCRIPTION":1,"TARIFF_CODE":456876,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":874,"CURRENTAGE":8,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":4356445,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3567,"CURRENTAGE":9,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":34566,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":45057,"CURRENTAGE":10,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":100,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":678,"CURRENTAGE":11,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":433456,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":854,"CURRENTAGE":12,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":45766,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":4563,"CURRENTAGE":13,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":100,"DESCRIPTION":1,"TARIFF_CODE":45866,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":0,"CURRENTAGE":14,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":43866,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":15,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":43467,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":5756,"CURRENTAGE":16,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":65437,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":987,"CURRENTAGE":17,"GENDER":1,"CLAIMED":344443,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":0,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":8234,"CURRENTAGE":0,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":5000,"DESCRIPTION":1,"TARIFF_CODE":457654,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":49503,"CURRENTAGE":1,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":547654,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":34590,"CURRENTAGE":2,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":54676,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3943,"CURRENTAGE":3,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":543766,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":4,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":666666,"DESCRIPTION":1,"TARIFF_CODE":536753,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3490,"CURRENTAGE":5,"GENDER":1,"CLAIMED":344345,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":753554,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3450,"CURRENTAGE":6,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":345978,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3745,"CURRENTAGE":7,"GENDER":1,"CLAIMED":56566,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":345545,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3450,"CURRENTAGE":8,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":345576,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":450,"CURRENTAGE":9,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":345567,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":345,"CURRENTAGE":10,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":34546,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":3453,"CURRENTAGE":11,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":3455,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":435,"CURRENTAGE":12,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":6553,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":345,"CURRENTAGE":13,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":64775,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":768,"CURRENTAGE":14,"GENDER":1,"CLAIMED":5656,"PRACTICE_NUMBER":576579,"DESCRIPTION":1,"TARIFF_CODE":34534,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":456,"CURRENTAGE":15,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":56756,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":765,"CURRENTAGE":16,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":59500,"DESCRIPTION":1,"TARIFF_CODE":65765,"Class":0},ignore_index=True)
train_dataset = train_dataset.append({"MEMBER_NUMBER":8697,"CURRENTAGE":17,"GENDER":1,"CLAIMED":18023,"PRACTICE_NUMBER":467687,"DESCRIPTION":1,"TARIFF_CODE":46546,"Class":0},ignore_index=True)


In [13]:
train_dataset.tail()


MEMBER_NUMBER  CURRENTAGE  GENDER  CLAIMED  PRACTICE_NUMBER  \
45903            345        13.0       1  18023.0            59500   
45904            768        14.0       1   5656.0           576579   
45905            456        15.0       1  18023.0            59500   
45906            765        16.0       1  18023.0            59500   
45907           8697        17.0       1  18023.0           467687   

       DESCRIPTION  TARIFF_CODE  Class  
45903            1        64775      0  
45904            1        34534      0  
45905            1        56756      0  
45906            1        65765      0  
45907            1        46546      0

In [14]:
train_dataset

MEMBER_NUMBER  CURRENTAGE  GENDER  CLAIMED  PRACTICE_NUMBER  \
0        30000246915   37.450782       1     50.0            18228   
1        30001796582   42.770674       1     40.0           188851   
2        30000517755   26.964222       1     50.0           186588   
3        30001471749    4.356696       0     40.0            12009   
4        30001378999   47.681964       1     50.0            18686   
...              ...         ...     ...      ...              ...   
45903            345   13.000000       1  18023.0            59500   
45904            768   14.000000       1   5656.0           576579   
45905            456   15.000000       1  18023.0            59500   
45906            765   16.000000       1  18023.0            59500   
45907           8697   17.000000       1  18023.0           467687   

       DESCRIPTION  TARIFF_CODE  Class  
0                1        90030      1  
1                1        58101      1  
2                1        59475      1  
3                0        96993      1  
4                1        90030      1  
...            ...          ...    ...  
45903            1        64775      0  
45904            1        34534      0  
45905            1        56756      0  
45906            1        65765      0  
45907            1        46546      0  

[45908 rows x 8 columns]

In [15]:
x = train_dataset.drop(columns = ['Class', 'MEMBER_NUMBER'], axis = 1)
y = train_dataset['Class']

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=42)


In [17]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(class_weight='balanced')
model.fit(x_train,y_train)

LogisticRegression(class_weight='balanced')

In [18]:
model.predict([[450,0,70,18023,1,59500]])

array([1], dtype=int64)

In [19]:
model.predict([[30,1,30,188851,1,59477]])

array([1], dtype=int64)

In [20]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()

In [21]:
x_train_smote, y_train_smote = smote.fit_resample(x_train.astype('float'),y_train)

In [22]:
model.fit(x_train_smote, y_train_smote)

LogisticRegression(class_weight='balanced')

In [23]:
model.predict([[0,0,30,1023,0,590]])

array([0], dtype=int64)

In [24]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
svm_clf = svm.SVC()
Naive_Bayes = GaussianNB()
knn = KNeighborsClassifier(n_neighbors=4)
model1 = RandomForestClassifier()
model2 = ExtraTreesClassifier()

In [25]:
model.fit(x_train_smote,y_train_smote)
model1.fit(x_train_smote,y_train_smote)
model2.fit(x_train_smote,y_train_smote)
svm_clf.fit(x_train_smote,y_train_smote)
Naive_Bayes.fit(x_train_smote,y_train_smote)
knn.fit(x_train_smote,y_train_smote)

KNeighborsClassifier(n_neighbors=4)

In [26]:
x_train_smote

CURRENTAGE  GENDER    CLAIMED  PRACTICE_NUMBER  DESCRIPTION  \
0       27.305620     1.0   25.00000         185744.0          1.0   
1       21.469599     1.0   25.00000         189412.0          1.0   
2        6.017986     1.0   70.00000          12807.0          0.0   
3        4.448093     1.0   80.00000          12440.0          0.0   
4        9.206158     0.0   80.00000          12149.0          0.0   
...           ...     ...        ...              ...          ...   
65557    3.609384     1.0  100.00000          12114.0          0.0   
65558   36.913147     1.0   80.00000          18082.0          1.0   
65559   33.134116     1.0   40.00000         183024.0          1.0   
65560    8.612096     0.0  100.00000          12580.0          0.0   
65561   61.730351     1.0   44.58986          18686.0          1.0   

        TARIFF_CODE  
0      59477.000000  
1      59477.000000  
2      90001.000000  
3      90000.000000  
4      90000.000000  
...             ...  
65557  90000.000000  
65558  90032.000000  
65559  59489.000000  
65560  90000.000000  
65561  90030.270507  

[65562 rows x 6 columns]

In [57]:
model1.predict([[15,1,20,180181,1,123455]])

array([0], dtype=int64)

In [58]:
import joblib
 
# Save the model as a pickle in a file
joblib.dump(model, 'logistics.pkl')
joblib.dump(model1, 'randForest.pkl')
joblib.dump(model2, 'extraTrees.pkl')
joblib.dump(svm_clf, 'svm.pkl')
joblib.dump(knn, 'knn.pkl')
joblib.dump(Naive_Bayes, 'gauss.pkl')


 
# Load the model from the file
#knn_from_joblib = joblib.load('filename.pkl')
 
# Use the loaded model to make predictions
#knn_from_joblib.predict(X_test)

['gauss.pkl']

In [52]:
knn_from_joblib = joblib.load('svm.pkl')
knn_from_joblib.predict([[40,0,70,18023,1,59500]])

array([1], dtype=int64)