In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import matplotlib
%matplotlib inline
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('Final_Dataset.csv')
df.head()

CLAIM_NUMBER  LINE_NUMBER  MEMBER_NUMBER  CURRENTAGE SUFFIX PATIENTNAME  \
0         31184            1    30400166634   39.921212      2  TASHINGA     
1         56041            1    30400171454   36.948093      1     EMILY     
2         86876            1    30001814165   38.128201      1    FADZAI     
3        117280            1    40000064456   60.203470      2    BHAVNA     
4        117281            1    40000064456   60.203470      2    BHAVNA     

  GENDER  CURRENTAGE_1  CLAIMED   PAID  ...  REFERRAL  PCKAGE TARIFF_AMOUNT  \
0      F     39.921212    450.0  258.0  ...   10782.0     304         258.0   
1      F     36.948093     70.0   17.5  ...    1244.0     304          25.0   
2      F     38.128201     25.0   17.5  ...    5058.0     300          25.0   
3      F     60.203470    300.0  135.0  ...   18192.0     400         135.0   
4      F     60.203470    200.0  200.0  ...   18192.0     400         250.0   

   PAY_WHO MODIFIER_STRING     FIRMNO SHORTFALLREASON PROVIDERTYPE       AGE  \
0        M             NaN  CMS004KAO             101           18  ABOVE 22   
1        M             NaN  CMS004MUR             101           18  ABOVE 22   
2        M             NaN  CMS001TNQ             101           18  ABOVE 22   
3        V             NaN  CMS001SHC         101;535           18  ABOVE 22   
4        V             NaN  CMS001SHC             101           18  ABOVE 22   

     Class  
0  proceed  
1  proceed  
2  proceed  
3  proceed  
4  proceed  

[5 rows x 32 columns]

In [6]:
df1 = df.drop(columns = ['LINE_NUMBER','SUFFIX','PATIENTNAME','CURRENTAGE_1','SHORTFALL', 'DATE_RECEIVED', 'PROCESS_DATE','PAYDATE','SERVICEDATE','DESCRIPTION_1','QUANTITY','REFERRAL','PCKAGE','PAY_WHO','MODIFIER_STRING','FIRMNO','SHORTFALLREASON','AGE'], axis = 1)

In [7]:
train_dataset = df1.drop(columns = ['SPE_SPECIALITY_CODE','PRACTICE_NAME','CLAIM_NUMBER','PROVIDERTYPE','TARIFF_AMOUNT','PAID'], axis = 1)

In [8]:
train_dataset = train_dataset.sample(frac=1).reset_index(drop=True)

In [12]:
train_dataset = train_dataset.replace({'GENDER':{'F':1,'M':0}})

In [13]:
train_dataset = train_dataset.replace({'Class':{'possible fraud ':0,'possible fraud':0, 'proceed':1}})

In [14]:
train_dataset

MEMBER_NUMBER  CURRENTAGE  GENDER  CLAIMED  PRACTICE_NUMBER  \
0        30002095841   29.539491       1     30.0           188851   
1        40000139247    4.913147       0     70.0            12003   
2        20001035064   32.595943       1     50.0           185744   
3        30002114194   38.837878       1     30.0            18228   
4        30000458426   27.948093       1     40.0            18023   
...              ...         ...     ...      ...              ...   
45849    30001042621   45.770674       1     60.0            18230   
45850    30002117775   40.673900       1     40.0            18023   
45851    30001746649   32.913147       1     40.0            18309   
45852    20000890671    4.028739       1     80.0            12089   
45853    30002122399    7.200782       1     35.0            12100   

                  DESCRIPTION  TARIFF_CODE  Class  
0      GYNAECOLOGY/OBSTETRICS        59477      1  
1              PAEDIATRICIANS        90003      1  
2      GYNAECOLOGY/OBSTETRICS        59475      1  
3      GYNAECOLOGY/OBSTETRICS        59477      1  
4      GYNAECOLOGY/OBSTETRICS        59477      1  
...                       ...          ...    ...  
45849  GYNAECOLOGY/OBSTETRICS        58101      1  
45850  GYNAECOLOGY/OBSTETRICS        59477      1  
45851  GYNAECOLOGY/OBSTETRICS        59477      1  
45852          PAEDIATRICIANS        90003      1  
45853          PAEDIATRICIANS        79017      1  

[45854 rows x 8 columns]

In [15]:
train_dataset = train_dataset.replace({'DESCRIPTION':{'GYNAECOLOGY/OBSTETRICS':1,'PAEDIATRICIANS':0}})

In [16]:
train_dataset

MEMBER_NUMBER  CURRENTAGE  GENDER  CLAIMED  PRACTICE_NUMBER  \
0        30002095841   29.539491       1     30.0           188851   
1        40000139247    4.913147       0     70.0            12003   
2        20001035064   32.595943       1     50.0           185744   
3        30002114194   38.837878       1     30.0            18228   
4        30000458426   27.948093       1     40.0            18023   
...              ...         ...     ...      ...              ...   
45849    30001042621   45.770674       1     60.0            18230   
45850    30002117775   40.673900       1     40.0            18023   
45851    30001746649   32.913147       1     40.0            18309   
45852    20000890671    4.028739       1     80.0            12089   
45853    30002122399    7.200782       1     35.0            12100   

       DESCRIPTION  TARIFF_CODE  Class  
0                1        59477      1  
1                0        90003      1  
2                1        59475      1  
3                1        59477      1  
4                1        59477      1  
...            ...          ...    ...  
45849            1        58101      1  
45850            1        59477      1  
45851            1        59477      1  
45852            0        90003      1  
45853            0        79017      1  

[45854 rows x 8 columns]

In [17]:
x = train_dataset.drop(columns = ['Class', 'MEMBER_NUMBER'], axis = 1)
y = train_dataset['Class']

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=42)


In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(class_weight='balanced')
model.fit(x_train,y_train)

LogisticRegression(class_weight='balanced')

In [20]:
model.predict([[0,1,70,18023,0,59500]])

array([0], dtype=int64)

In [23]:
model.predict([[30,1,30,188851,1,59477]])

array([1], dtype=int64)

In [24]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()

In [26]:
x_train_smote, y_train_smote = smote.fit_resample(x_train.astype('float'),y_train)

In [27]:
model.fit(x_train_smote, y_train_smote)

LogisticRegression(class_weight='balanced')

In [36]:
model.predict([[0,0,30,1023,0,590]])

array([1], dtype=int64)

In [37]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
svm_clf = svm.SVC()
Naive_Bayes = GaussianNB()
knn = KNeighborsClassifier(n_neighbors=4)
model1 = RandomForestClassifier()
model2 = ExtraTreesClassifier()

In [38]:
model.fit(x_train_smote,y_train_smote)
model1.fit(x_train_smote,y_train_smote)
model2.fit(x_train_smote,y_train_smote)
svm_clf.fit(x_train_smote,y_train_smote)
Naive_Bayes.fit(x_train_smote,y_train_smote)
knn.fit(x_train_smote,y_train_smote)

KNeighborsClassifier(n_neighbors=4)

In [39]:
import joblib
 
# Save the model as a pickle in a file
joblib.dump(model, 'logistics.pkl')
joblib.dump(model1, 'randForest.pkl')
joblib.dump(model2, 'extraTrees.pkl')
joblib.dump(svm_clf, 'svm.pkl')
joblib.dump(knn, 'knn.pkl')
joblib.dump(Naive_Bayes, 'gauss.pkl')


 
# Load the model from the file
#knn_from_joblib = joblib.load('filename.pkl')
 
# Use the loaded model to make predictions
#knn_from_joblib.predict(X_test)

['gauss.pkl']

In [52]:
knn_from_joblib = joblib.load('svm.pkl')
knn_from_joblib.predict([[40,0,70,18023,1,59500]])

array([1], dtype=int64)